/* Default Open Graph card for FileMayor pages.
   Generated by next/og at build time and on demand for any route that
   doesn't override it. 1200x630, dark warm canvas, Newsreader-feeling
   serif headline plus mono metadata. */

import { ImageResponse } from 'next/og';
import { site } from '@/lib/site';

export const runtime = 'edge';
export const alt = `${site.name} — ${site.tagline}`;
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

export default async function OpenGraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          background: '#0d0b0a',
          padding: '80px',
          color: '#fafaf8',
        }}
      >
        {/* Top row — wordmark + version */}
        <div
          style={{
            display: 'flex',
            alignItems: 'baseline',
            justifyContent: 'space-between',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'baseline', gap: '14px' }}>
            <span style={{ fontFamily: 'serif', fontSize: 42, letterSpacing: '-0.02em' }}>
              {site.name}
            </span>
            <span
              style={{
                fontFamily: 'monospace',
                fontSize: 14,
                color: '#71746e',
                letterSpacing: '0.18em',
                textTransform: 'uppercase',
              }}
            >
              — by {site.by}
            </span>
          </div>
          <span
            style={{
              fontFamily: 'monospace',
              fontSize: 14,
              color: '#d4af37',
              letterSpacing: '0.18em',
              textTransform: 'uppercase',
            }}
          >
            v{site.version}
          </span>
        </div>

        {/* Centered headline */}
        <div
          style={{
            flex: 1,
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
          }}
        >
          <h1
            style={{
              fontFamily: 'serif',
              fontSize: 108,
              lineHeight: 1.02,
              letterSpacing: '-0.025em',
              fontWeight: 400,
              margin: 0,
              maxWidth: 980,
            }}
          >
            The doctor for your{' '}
            <em style={{ color: '#d4af37', fontStyle: 'italic' }}>filesystem</em>.
          </h1>
          <p
            style={{
              marginTop: 32,
              fontFamily: 'sans-serif',
              fontSize: 28,
              lineHeight: 1.45,
              color: '#a8a59e',
              maxWidth: 720,
            }}
          >
            {site.description}
          </p>
        </div>

        {/* Bottom row — verb chain */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '20px',
            fontFamily: 'monospace',
            fontSize: 18,
            color: '#a8a59e',
            letterSpacing: '0.04em',
          }}
        >
          <span style={{ color: '#d4af37' }}>scan</span>
          <span style={{ color: '#71746e' }}>→</span>
          <span style={{ color: '#d4af37' }}>explain</span>
          <span style={{ color: '#71746e' }}>→</span>
          <span style={{ color: '#d4af37' }}>cure</span>
          <span style={{ color: '#71746e' }}>→</span>
          <span style={{ color: '#d4af37' }}>apply</span>
          <span style={{ color: '#71746e' }}>→</span>
          <span style={{ color: '#d4af37' }}>undo</span>
        </div>
      </div>
    ),
    { ...size },
  );
}
