/* Default Open Graph card for FileMayor pages.
   Generated by next/og at build time and on demand for any route that
   doesn't override it. 1200x630 — mirrors the live hero: dark warm canvas,
   serif headline with gold accent, trust stats, PARA bucket colour bar. */

import { ImageResponse } from 'next/og';
import { site } from '@/lib/site';

export const runtime = 'edge';
export const alt = `${site.name} — ${site.tagline}`;
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

const stats: [string, string][] = [
  ['25k+', 'installs'],
  ['128', 'tests passing'],
  ['0', 'runtime vulns'],
  ['100%', 'free · reversible'],
];

const buckets = ['#38bdf8', '#f59e0b', '#34d399', '#a78bfa'];

export default async function OpenGraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          background: 'linear-gradient(135deg, #0d0b0a 0%, #14100d 60%, #1a140e 100%)',
          padding: '72px 80px',
          color: '#fafaf8',
          position: 'relative',
        }}
      >
        {/* gold aurora */}
        <div
          style={{
            position: 'absolute',
            top: -140,
            right: -80,
            width: 620,
            height: 480,
            background: 'radial-gradient(ellipse at center, rgba(212,175,55,0.22), transparent 65%)',
            display: 'flex',
          }}
        />

        {/* Top row — wordmark + version */}
        <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'baseline', gap: '14px' }}>
            <span style={{ fontFamily: 'serif', fontSize: 44, letterSpacing: '-0.02em' }}>
              {site.name}
            </span>
            <span
              style={{
                fontFamily: 'monospace', fontSize: 14, color: '#71746e',
                letterSpacing: '0.18em', textTransform: 'uppercase',
              }}
            >
              — by {site.by}
            </span>
          </div>
          <span
            style={{
              fontFamily: 'monospace', fontSize: 14, color: '#d4af37',
              letterSpacing: '0.18em', textTransform: 'uppercase',
            }}
          >
            v{site.version} · AI file organizer
          </span>
        </div>

        {/* Centered headline — mirrors the hero */}
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
          <h1
            style={{
              fontFamily: 'serif', fontSize: 116, lineHeight: 1.02,
              letterSpacing: '-0.03em', fontWeight: 400, margin: 0, maxWidth: 1000,
              display: 'flex', flexWrap: 'wrap', gap: '0 26px',
            }}
          >
            <span>Your folders,</span>
            <em style={{ color: '#d4af37' }}>on command.</em>
          </h1>
          <p
            style={{
              marginTop: 30, fontFamily: 'sans-serif', fontSize: 27,
              lineHeight: 1.45, color: '#a8a59e', maxWidth: 760,
            }}
          >
            Shows you the plan before it moves a thing — then undoes the whole
            session with one command. Mac · Windows · Linux.
          </p>
          {/* PARA bucket colour bar */}
          <div style={{ display: 'flex', gap: 10, marginTop: 34 }}>
            {buckets.map((c) => (
              <div key={c} style={{ width: 74, height: 7, borderRadius: 4, background: c, display: 'flex' }} />
            ))}
          </div>
        </div>

        {/* Bottom row — trust stats */}
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 44 }}>
          {stats.map(([v, l]) => (
            <div key={l} style={{ display: 'flex', alignItems: 'baseline', gap: 10 }}>
              <span style={{ fontFamily: 'serif', fontSize: 30, color: '#fafaf8' }}>{v}</span>
              <span
                style={{
                  fontFamily: 'monospace', fontSize: 13, color: '#71746e',
                  letterSpacing: '0.14em', textTransform: 'uppercase',
                }}
              >
                {l}
              </span>
            </div>
          ))}
        </div>
      </div>
    ),
    { ...size },
  );
}
